defaults:
  - prtreid
  - _self_

# ReID configuration for 38% GS-HOTA performance
# Based on the successful commit that achieved GS_HOTA 38 using baseline

# Training configuration
training_enabled: False  # Use pre-trained model
batch_size: 64

# Model configuration
cfg:
  project:
    name: "TrackLab"
    entity: ""
    tags: []
    logger:
      use_tensorboard: True
      use_wandb: True  # Enable wandb logging
  
  model:
    name: "bpbreid"
    pretrained: True  # Use pre-trained model
    save_model_flag: True
    load_config: True
    # Note: The baseline model file is missing, but we'll use the best available
    load_weights: ""  # Will use default pre-trained weights
  
  test:
    evaluate: True  # Enable evaluation
    detailed_ranking: False
    start_eval: 10
    batch_size_pairwise_dist_matrix: 5000
    normalize_feature: True
    dist_metric: "euclidean"
    visrank: False  # Disable for faster processing
