defaults:
  - soccernet
  - _self_

# 🚀 OPTIMIZED BASELINE CONFIGURATION: Achieve >38% GS-HOTA
# Goal: Build upon the proven baseline success with additional optimizations

# Machine configuration
use_wandb: True
use_rich: True

# Dataset configuration for focused processing
dataset:
  nvid: 1  # Process only 1 video for focused optimization
  eval_set: "valid"  # Use validation set
  vids_dict:
    valid: []  # Let it auto-select the best video

# OPTIMIZED BASELINE APPROACH: Use proven modules with enhanced parameters
modules:
  # 🎯 Use default mmocr for jersey detection (baseline approach that worked)
  jersey_number_detect: mmocr
  
  # 🔧 Use optimized ReID configuration from successful baseline
  reid: prtreid_baseline_38
  
  # 🎯 AGGRESSIVE detection optimization for maximum recall
  bbox_detector:
    batch_size: 4  # Smaller batch for better memory usage
    conf_threshold: 0.1  # Very low confidence threshold for maximum recall
    iou_threshold: 0.4   # Lower IoU threshold for more detections
  
  # 🎯 Optimize tracking parameters
  track:
    batch_size: 32  # Balanced batch size for tracking

# Visualization for analysis
visualization:
  cfg:
    save_videos: True  # Save videos for analysis

# Experiment naming
experiment_name: "sn-gamestate-baseline-38-optimized"
