# TrackLab SoccerNet config with Unified Backbone Option
# This file shows how to use the unified backbone instead of separate modules
# while maintaining the same pipeline structure

# The defaults list contains the files that will be used
# to create the final config file. This item *must* be
# the first element in the file.
defaults:
  - dataset: soccernet_gs
  - eval: gs_hota
  - engine: offline
  - visualization: gamestate
  
  # OPTION 1: Use unified backbone (recommended for better performance)
  - modules/unified_backbone: unified_backbone
  
  # OPTION 2: Use separate modules (original approach)
  # - modules/bbox_detector: yolo_ultralytics
  # - modules/pitch: nbjw_calib
  # - modules/calibration: nbjw_calib
  
  # Other modules remain the same
  - modules/reid: prtreid
  - modules/track: bpbreid_strong_sort
  - modules/jersey_number_detect: mmocr
  - modules/team: kmeans_embeddings
  - modules/team_side: mean_position
  - modules/tracklet_agg: voting_role_jn
  
  - _self_

# Pipeline definition:
# With unified backbone: single module handles detection + pitch + calibration
# With separate modules: three separate modules in sequence
pipeline:
  # OPTION 1: Unified backbone (single module)
  - unified_backbone
  
  # OPTION 2: Separate modules (original approach)
  # - bbox_detector
  # - pitch
  # - calibration
  
  # Other modules remain the same
  - reid
  - track
  - jersey_number_detect
  - tracklet_agg
  - team
  - team_side

# Experiment name
experiment_name: "sn-gamestate-unified-option"

# Path definitions
home_dir: "${oc.env:HOME}"
data_dir: "/netscratch/eattar/ds/SoccerNet/2024/data"
model_dir: "${project_dir}/pretrained_models"

# Machine configuration
num_cores: 1
use_wandb: True
use_rich: True

modules:
  # Unified backbone configuration
  unified_backbone: 
    batch_size: 1
    backbone_type: "resnet50"
    temporal_frames: 5
    use_attention: true
    detection_threshold: 0.5
    pitch_threshold: 0.3
  
  # Other module configurations
  pose_bottomup: {batch_size: 8}
  reid: {batch_size: 64}
  track: {batch_size: 64}
  jersey_number_detect: {batch_size: 8}

# Flags
test_tracking: True
eval_tracking: True
print_config: True

# Dataset
dataset:
  nvid: 1
  eval_set: "valid"
  dataset_path: ${data_dir}/SoccerNetGS
  vids_dict:
    valid: []

# Tracker state
state:
  save_file: "states/${experiment_name}.pklz"
  load_file: null

# Visualization
visualization:
  cfg:
    save_videos: True

# Hydra configuration
project_dir: "${hydra:runtime.cwd}"
hydra:
  output_subdir: "configs"
  job:
    chdir: True
  run:
    dir: "/netscratch/eattar/SoccerNet/outputs/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}"
  sweep:
    dir: "multirun_outputs/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}"
