# Optimized SoccerNet configuration for improved detection performance
# Focus: Boost detection recall from 14.105% to 25-30%

# Inherit from base configuration
defaults:
  - soccernet
  - modules/jersey_number_detect/improved_mmocr_optimized
  - _self_

# Experiment configuration
experiment_name: "sn-gamestate-improved-jersey-optimized-v3"
use_wandb: false
use_rich: true

# Dataset configuration
dataset:
  vids_dict:
    valid: []  # Auto-select first available video
    # To find valid video IDs, run with empty list first, then check the output directory for the processed video name

# Core pipeline modules
pipeline:
  - bbox_detector
  - reid
  - track
  - pitch
  - calibration
  - jersey_number_detect
  - tracklet_agg
  - team
  - team_side

# Optimized batch sizes for better quality
bbox_detector:
  batch_size: 4  # Reduced from 6 for better detection quality
  conf_threshold: 0.25  # Lower confidence threshold for more detections
  iou_threshold: 0.45   # Optimized IoU threshold

pose_bottomup:
  batch_size: 4  # Reduced from 6 for better quality

reid:
  batch_size: 32  # Reduced from 48 for better quality

track:
  batch_size: 32  # Reduced from 48 for better quality

jersey_number_detect:
  batch_size: 8  # Optimized for jersey detection

# Detection optimization flags
optimize_detection: true
optimize_tracking: true
optimize_jersey: true

# Advanced detection parameters
detection:
  enable_multi_scale: true
  enable_tta: false  # Test Time Augmentation (can be slow)
  min_detection_size: 20  # Minimum bounding box size
  max_detection_size: 800  # Maximum bounding box size

# Tracking optimization
tracking:
  enable_velocity_prediction: true
  enable_appearance_matching: true
  min_track_length: 3  # Minimum frames for valid track

# Jersey recognition optimization
jersey_optimization:
  enable_confidence_smoothing: true
  enable_temporal_consistency: true
  enable_quality_bonuses: true
  min_sequence_quality: 0.3
  min_temporal_score: 0.3

# Performance monitoring
monitoring:
  log_detection_stats: true
  log_tracking_stats: true
  log_jersey_stats: true
  save_intermediate_results: true
