# TrackLab SoccerNet config with Improved Jersey Recognition and Detection Optimization

# The defaults list contains the files that will be used
# to create the final config file. This item *must* be
# the first element in the file.
defaults:
  - dataset: soccernet_gs
  - eval: gs_hota
  - engine: offline
  - visualization: gamestate
  - modules/bbox_detector: yolo_ultralytics
  - modules/reid: prtreid
  - modules/track: bpbreid_strong_sort
  - modules/jersey_number_detect: improved_mmocr_simple  # Using improved jersey recognition
  - modules/team: kmeans_embeddings
  - modules/team_side: mean_position
  - modules/tracklet_agg: voting_role_jn
  - modules/pitch : nbjw_calib
  - modules/calibration: nbjw_calib
  - _self_

# Pipeline definition
pipeline:
  - bbox_detector
  - reid
  - track
  - pitch
  - calibration
  - jersey_number_detect
  - tracklet_agg
  - team
  - team_side

# Experiment name
experiment_name: "sn-gamestate-improved-jersey-working-v3"

# Path definitions
home_dir: "${oc.env:HOME}"
data_dir: "/netscratch/eattar/ds/SoccerNet/2024/data"
model_dir: "${project_dir}/pretrained_models"

# Machine configuration
num_cores: 1
use_wandb: False
use_rich: True

# Optimization flags
optimize_detection: True
optimize_tracking: True
optimize_jersey: True

# Optimized batch sizes for better quality
modules:
  bbox_detector: {batch_size: 4}  # Reduced for better detection quality
  pose_bottomup: {batch_size: 4}  # Reduced for better quality
  reid: {batch_size: 32}  # Reduced for better quality
  track: {batch_size: 32}  # Reduced for better quality
  pitch: {batch_size: 1}
  calibration: {batch_size: 1}
  jersey_number_detect: {batch_size: 8}  # Optimized for jersey detection

# Flags
test_tracking: True
eval_tracking: True
print_config: True

# Dataset
dataset:
  nvid: 1  # Process only 1 video for faster testing
  eval_set: "valid"
  dataset_path: ${data_dir}/SoccerNetGS
  vids_dict:
    valid: []  # Auto-select first available video

# Tracker state
state:
  save_file: null  # Disable saving to force fresh computation
  load_file: null  # Disable loading from previous runs

# Visualization
visualization:
  cfg:
    save_videos: True

# configure Hydra to use the current working directory
project_dir: "${hydra:runtime.cwd}"
hydra:
  output_subdir: "configs"
  job:
    chdir: True
  run:
    dir: "/netscratch/eattar/SoccerNet/outputs/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}"
  sweep:
    dir: "multirun_outputs/${experiment_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}"
