defaults:
  - soccernet
  - _self_

# 🚀 BASELINE 38% + JERSEY ENHANCEMENT: Achieve >38% GS-HOTA
# Goal: Use the EXACT detection parameters that achieved 38% GS-HOTA + your jersey improvements

# Machine configuration
use_wandb: True
use_rich: True

# Dataset configuration for focused processing
dataset:
  nvid: 1  # Process only 1 video for focused optimization
  eval_set: "valid"  # Use validation set
  vids_dict:
    valid: []  # Let it auto-select the best video

# BASELINE 38% SUCCESS + JERSEY ENHANCEMENT
modules:
  # 🎯 KEY INNOVATION: Use improved jersey recognition for better accuracy
  jersey_number_detect:
    _target_: sn_gamestate.jersey.improved_jersey_recognition.ImprovedJerseyRecognition
    batch_size: 16
    sequence_length: 7
    min_confidence_threshold: 0.15
    min_sequence_confidence: 0.25
    temporal_weight: 0.8
    spatial_weight: 0.2
    use_confidence_boost: true
    enable_aggressive_boosting: true
  
  # 🔧 Use the EXACT detection parameters that achieved 38% GS-HOTA
  bbox_detector:
    batch_size: 4  # Smaller batch for better memory usage
    conf_threshold: 0.1  # VERY LOW confidence threshold (like baseline success)
    iou_threshold: 0.4   # Lower IoU threshold for more detections
  
  # 🎯 Optimize tracking parameters
  track:
    batch_size: 32  # Balanced batch size for tracking

# Visualization for analysis
visualization:
  cfg:
    save_videos: True  # Save videos for analysis

# Experiment naming
experiment_name: "sn-gamestate-baseline-38-jersey-enhanced"
