_target_: sn_gamestate.jersey.improved_jersey_recognition.ImprovedJerseyRecognition
batch_size: 16  # Good for GPU utilization
sequence_length: 7  # Increased for better temporal consistency and context (7 frames = better analysis)
min_confidence_threshold: 0.15  # Lowered threshold to catch more detections and improve recall
temporal_weight: 0.9  # Increased weight for temporal consistency (was 0.8)
spatial_weight: 0.1   # Reduced weight for spatial factors (was 0.2)
use_confidence_boost: true  # Enable confidence boosting for consistent detections
min_sequence_confidence: 0.25  # Lowered minimum confidence for sequence aggregation (was 0.3)
enable_aggressive_boosting: true  # Enable more aggressive confidence boosting
