_target_: sn_gamestate.jersey.improved_jersey_recognition.ImprovedJerseyRecognition
batch_size: 16  # Increased for better GPU utilization
sequence_length: 2  # Minimal sequence length for speed
min_confidence_threshold: 0.5  # Higher threshold = fewer detections to process
temporal_weight: 0.5  # Simplified weighting
spatial_weight: 0.5  # Simplified weighting
