_target_: sn_gamestate.jersey.improved_jersey_recognition.ImprovedJerseyRecognition
batch_size: 16  # Good for GPU utilization
sequence_length: 5  # Increased for better temporal consistency (5 frames = better analysis)
min_confidence_threshold: 0.2  # Lower threshold to catch more valid detections
temporal_weight: 0.8  # Higher weight for temporal consistency
spatial_weight: 0.2   # Lower weight for spatial factors
use_confidence_boost: true  # Enable confidence boosting for consistent detections
min_sequence_confidence: 0.3  # Lower minimum confidence for sequence aggregation
enable_aggressive_boosting: true  # Enable more aggressive confidence boosting
