# Simple configuration for improved jersey recognition
# Focus: Basic optimization with currently supported parameters

# Core parameters
batch_size: 8  # Reduced for better quality
sequence_length: 5  # Balanced between quality and coverage

# Confidence thresholds - LOWER for more detections
min_confidence_threshold: 0.1  # Was 0.15 - lower for more detections
min_sequence_confidence: 0.2   # Was 0.25 - lower for more sequences

# Temporal vs spatial weighting
temporal_weight: 0.85  # Was 0.9 - slightly reduce temporal dominance
spatial_weight: 0.15   # Was 0.1 - increase spatial importance

# Confidence boosting strategies
use_confidence_boost: true
enable_aggressive_boosting: true
